### ISSUE TITLE
Logger timestamp support timezone setting

### ISSUE THREAD

**Issue by hkicl-ming** [rtang03/fabric-es#200]
Currently, the timestamp of log output is in UTC format
`2021-03-25T10:03:06.641Z [info]: 🚀 gateway ready at http://gw-org1:4001/graphql ([gw-org1] app.js)`

It is nice to have a function to set the timestamp of log in specific region (Eg. Hong Kong)
`2021-03-25T18:02:57+08:00 [info]: 🚀 admin service ready at http://localhost:15011/graphql (service-admin.js)`

Example
https://medium.com/front-end-weekly/node-js-logs-in-local-timezone-on-morgan-and-winston-9e98b2b9ca45

Sample of modification in getLogger.ts
```
// using moment-timezone package
var moment = require('moment-timezone');

//...

// timezone setting
const appendTimestamp = format((info, opts) => {
  if (opts.tz) info.timestamp = moment().tz(opts.tz).format();
  return info;
});

//...

// set the timezone value when createLogger
    loggers[name] = createLogger({
      level,
      exitOnError: false,
      format: combine(label({ label: name }), appendTimestamp({ tz: 'Asia/Hong_Kong' }), logFormat),
      transports: transportArray,
    });
```

**Comment by hkicl-ming** [comment]
@rtang03 change is straight forward, does it require test case?

**Comment by rtang03** [comment]
No test case is fine

**Comment by hkicl-ming** [comment]
TimeZone value will be 
- input with arg `timezone` when initiate getLogger or
- setting environment variable `TZ` to override the default value or
- default value is `Asia/Hong_Kong` when none of above is set
