### ISSUE TITLE
Add an enrollOnly function in operator

### ISSUE THREAD

**Issue by rtang03** [rtang03/fabric-es#225]
For trouble shooting purpose, we "RE-enrol" the CA user from CA Server, but not new create a new user.

Two areas of improvement:
- add gpl endpoint in gateway-lib, "enrollUser". 
- add new "enrollUser", function in operator/tasks/registerAndEnroll,

**Comment by hkicl-ming** [comment]
Can it simply reuse the `createWallet` function with passing a flag “enroll only” to serve the purpose?
